# Generated by Django 3.2.3 on 2022-01-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='quantity of items')),
                ('price', models.FloatField(max_length=100, verbose_name='price of the item')),
                ('expiry', models.DateTimeField(verbose_name='expiry time')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='unique id')),
                ('name', models.CharField(max_length=1000, verbose_name='name of the product')),
                ('quantity', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='quantity of items')),
                ('price', models.FloatField(max_length=100, verbose_name='price of the item')),
                ('currency_name', models.CharField(max_length=10, verbose_name='currency name')),
                ('deal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deals')),
            ],
        ),
    ]
